name: Release

on:
  push:
    branches:
      - main

# Comment 2
jobs:
  release:
    # ensure it does not run when the repo is generated (main branch created)
    if: github.event.created == false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - name: Add plugin for conventional commits
      run: npm install conventional-changelog-conventionalcommits
      working-directory: ./.github/workflows
    - name: Create .releaserc file
      uses: "DamianReeves/write-file-action@master"
      with:
        path: ./.github/workflows/.releaserc 
        write-mode: overwrite
        contents: |
          ---
          branches:
          - main
          ci: true
          private: true
          npmPublish: false
          repository:
            type: git
            url: "git@github.com:claudiosaavedr/test-template.git"
          plugins:
          - - "@semantic-release/commit-analyzer"
            - preset: conventionalcommits
          - - "@semantic-release/release-notes-generator"
            - preset: conventionalcommits
          - - "@semantic-release/github"
    - name: Release to GitHub
      working-directory: ./.github/workflows
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_AUTHOR_NAME: enter author name
        GIT_AUTHOR_EMAIL: person@example.com
        GIT_COMMITTER_NAME: enter name
        GIT_COMMITTER_EMAIL: committer@example.com
      run: npx semantic-release

